version: '3.5'
services:

  backend:
    image: backimage
    ports:
      - "4000:4000"
    volumes:
      - ./backend/logs:/app/logs  # Map the logs directory in the container to the ./backend/logs directory on the host


  frontend:
    image: frontimage
    ports:
      - "3000:3000"
    depends_on:
      - backend

  #   depends_on:
  #     - mongodb

  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - /home/ak232003/expense-tracker_fullstack/data/db:/data/db:rw