version: '3.5'
services:

  backend:
    image: anwit/backimage
    ports:
      - "4000:4000"
    volumes:
      - ./backend/logs:/app/logs  # Map the log directory in the container to the ./backend/logs directory on the host
    depends_on:
      - mydatabase
    networks:
      - my-network

  frontend:
    image: anwit/frontimage
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network

  mydatabase:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db:rw
    networks:
      - my-network

networks:
  my-network:
    driver: bridge