version: '3.5'
services:

  backend:
    image: backimage
    ports:
      - "4000:4000"
    volumes:
      - ./backend/logs:/app/logs  # Map the log directory in the container to the ./backend/logs directory on the host
    depends_on:
      - mydatabase

  frontend:
    image: frontimage
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mydatabase:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db:rw